### ISSUE TITLE
[Feature Request]: Add Missing Meta Tags, robots.txt, sitemaps for SEO Enhancement

### ISSUE THREAD

**Issue by itshivams** [Swarnendu0123/adopt-pet#33]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The current project lacks essential meta tags that are crucial for search engine optimization (SEO). To improve the visibility and ranking of the website on search engines

or social media sharing
Robots meta tag

and have to add sitemap.xml and robots file for search engine to crawl our site.

### Use Case

we need to add the following missing meta tags:

Title tags
Description tags
Keywords tags
Open Graph tags f

### Benefits

SEO enhance, search engine can crawl our site

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 Extd contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.
